spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  cloud:
    config:
      import-check:
        enabled: false
  config:
    import: "optional:configserver:http://localhost:8071/"

